server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: ms-assessment
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  cloud:
    compatibility-verifier:
      enabled: false
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:w7V9s2G8h4L3p9J6qX1vZ0nA5rT8uK2mF0yP3bQ7sD1eR4xV}

MS_COURSE_URL: ${MS_COURSE_URL:http://localhost:8082}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true