server:
  port: 8083
  forward-headers-strategy: framework

spring:
  application:
    name: ms-content
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  cloud:
    compatibility-verifier:
      enabled: false
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:w7V9s2G8h4L3p9J6qX1vZ0nA5rT8uK2mF0yP3bQ7sD1eR4xV}

minio:
  url: ${MINIO_URL:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:admin123}
  bucket-name: ${MINIO_BUCKET_NAME:content}
  public-url: ${MINIO_PUBLIC_URL:http://localhost:9000}

MS_COURSE_URL: ${MS_COURSE_URL:http://localhost:8082}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true